### ISSUE TITLE
ERROR Execution error getMe: request call:

### ISSUE THREAD

**Issue by qlikwer** [kotopheiop/telegram-sender#1]
Allo! Developer!!
Error! Error!

app_1  | [Thu Nov 23 04:40:21 UTC 2023] ERROR Execution error getMe: request call: fasthttp do request: dialing to the given TCP address timed out
app_1  | telego: getMe(): internal execution: request call: fasthttp do request: dialing to the given TCP address timed out
app_1  | Сервис запустился на адресе localhost:8080

**Comment by kotopheiop** [comment]
Обновил инструкцию по подготовке к запуску сервиса
Исключил стороннюю библиотеку для работа с API Telegram
Исключил работу с файлом `.env`, передача токена теперь через environment в `docker-compose.yml`
